[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = [
    "data-structures",
    "no-std",
]
description = "`static` friendly data structures that don't require dynamic memory allocation"
documentation = "https://docs.rs/heapless"
keywords = [
    "static",
    "no-heap",
]
license = "MIT OR Apache-2.0"
name = "heapless"
repository = "https://github.com/japaric/heapless"
version = "0.2.0"

[dependencies]
untagged-option = "0.1.1"
